import type { Metadata } from "next";
import Link from "next/link";
import {
  formatPaise,
  isMaterialEnabled,
  MATERIAL_IDS,
  materialName,
  isCustomMaterial,
  type StockMaterialId,
} from "@print/shared";
import { PageIntro } from "@/components/shell/page-intro";
import { getCatalogAvailability } from "@/lib/catalog-availability";
import { getPricing } from "@/lib/pricing-settings";
import { getSiteProfile } from "@/lib/site-profile";

export async function generateMetadata(): Promise<Metadata> {
  const { brandName } = await getSiteProfile();
  return {
    title: "Pricing",
    description: `How ${brandName} quotations are calculated: real slicing data, per-gram rates, one transparent setup fee.`,
  };
}

export const dynamic = "force-dynamic";

const MATERIAL_BLURB: Record<StockMaterialId, string> = {
  PLA: "The everyday material — crisp detail, easy on the wallet.",
  PLA_AESTHETIC: "Silk, matte, metallic, starlight, glow-in-the-dark and wood finishes for display pieces.",
  PLA_CF: "Carbon-fibre-filled PLA — stiff, matte, and dimensionally stable.",
  PETG: "Tougher, heat-resistant parts for real-world use.",
  PETG_PREMIUM: "Translucent and glitter PETG, plus carbon-fibre PETG for rigid functional parts.",
  ABS: "Heat-tolerant and impact-tough, for functional parts near engines, lamps and electronics.",
  ASA: "ABS's weatherproof sibling — holds its colour and strength outdoors and in the sun.",
};

export default async function PricingPage() {
  const [{ catalog }, availability] = await Promise.all([getPricing(), getCatalogAvailability()]);
  const { setupFeePaise, materials, electricityPerKwhPaise, maintenancePerGramPaise, printers } =
    catalog;
  const printer = printers[catalog.defaultPrinterId]!;
  const shownMaterials = MATERIAL_IDS.filter((m) => isMaterialEnabled(availability, m));

  return (
    <div className="mx-auto max-w-6xl px-5 py-16 sm:py-20">
      <PageIntro
        eyebrow="Pricing"
        title="No mystery math"
        lede="Every quote is generated by actually slicing your model with the same profile the printer runs. You pay for the grams the slicer says your part needs — nothing hidden."
      />

      <section className="mx-auto mt-12 max-w-3xl" aria-labelledby="rates-title">
        <h2 id="rates-title" className="section-title">
          The rates
        </h2>
        <div className="mt-6 grid gap-4 sm:grid-cols-3">
          <div className="tile p-5">
            <p className="eyebrow text-[0.7rem]">Setup fee</p>
            <p className="mt-2 text-2xl font-[650] tracking-tight">{formatPaise(setupFeePaise)}</p>
            <p className="mt-1 text-sm text-muted">Once per order, however many files you upload.</p>
          </div>
          {shownMaterials.map((m) => (
            <div key={m} className="tile p-5">
              <p className="eyebrow text-[0.7rem]">{materialName(m, availability.customMaterials)}</p>
              <p className="mt-2 text-2xl font-[650] tracking-tight">
                {formatPaise(materials[m].sellPerGramPaise)}
                <span className="text-sm font-[450] text-muted"> / gram</span>
              </p>
              <p className="mt-1 text-sm text-muted">
                {isCustomMaterial(m) ? "Ask us about this material's properties." : MATERIAL_BLURB[m]}
              </p>
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto mt-14 max-w-3xl" aria-labelledby="how-title">
        <h2 id="how-title" className="section-title">
          How a quote is built
        </h2>
        <ol className="mt-6 space-y-4">
          {[
            {
              t: "Your file is sliced for real",
              b: `The backend runs OrcaSlicer with a genuine ${printer.name} profile at your chosen layer height, infill and support settings. The slicer reports exactly how many grams of filament and minutes of print time your part needs.`,
            },
            {
              t: "Grams × rate + setup fee",
              b: "Your price is the slicer's filament weight multiplied by the per-gram rate for your material, times quantity, plus the one-time setup fee. Change a setting and the model is re-sliced — the price you see always matches real toolpaths.",
            },
            {
              t: "The breakdown is honest",
              b: `We show you what the per-gram rate covers: filament cost, roughly ${formatPaise(electricityPerKwhPaise)}/kWh of electricity (the printer draws about ${printer.kwhPerHour} kWh per print-hour) and a ${formatPaise(maintenancePerGramPaise)}/g maintenance allocation for nozzles, plates and wear. These are informational — they're already inside the rate, never added on top.`,
            },
          ].map((item, i) => (
            <li key={item.t} className="tile p-5">
              <div className="flex items-baseline gap-3">
                <span className="font-mono text-xs text-accent">0{i + 1}</span>
                <div>
                  <h3 className="text-[0.95rem] font-[650]">{item.t}</h3>
                  <p className="mt-1.5 text-sm leading-6 text-muted">{item.b}</p>
                </div>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section className="mx-auto mt-14 max-w-3xl" aria-labelledby="phil-title">
        <h2 id="phil-title" className="section-title">
          Pricing philosophy
        </h2>
        <p className="mt-4 text-[0.95rem] leading-7 text-muted">
          Quotes from this tool are estimates built on real slicing data, and they're the number we
          stand behind in the WhatsApp conversation that follows. If a part needs special handling —
          brittle overhangs, tight tolerances, post-processing — we'll say so before printing, not
          after. No surcharges appear that weren't discussed.
        </p>
        <Link href="/quote" className="btn-pill mt-8">
          Try it with your model
        </Link>
      </section>
    </div>
  );
}
